import '../testSupport/silenceServiceLogs.js'; // must be first: see file comment
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { diffRangeArgs, collectDiffFiles, collectDiffWithMeta } from '../src/tools/diff.js';
import { retrievalQueryFor } from '../src/tools/reviewScope.js';

const exec = promisify(execFile);

/**
 * What `range` actually means.
 *
 * `git diff --unified=3 main..HEAD` is a two-dot diff: when `main` has moved on
 * since the branch was cut, it reports main's own commits INVERTED, as though
 * the change under review deleted them. A review means "what this branch did",
 * which is the three-dot / merge-base form. The reviewed merge request happened
 * to have its base at the merge base, so the bug was invisible there.
 */

/** main advances after `feature` is cut — the case two-dot gets wrong. */
async function divergedRepo() {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'repospector-diverge-'));
    const git = (...args) => exec('git', args, { cwd: dir });

    await git('init', '-q', '-b', 'main');
    await git('config', 'user.email', 'test@example.com');
    await git('config', 'user.name', 'test');

    await fs.writeFile(path.join(dir, 'base.js'), 'export const base = 1;\n');
    await git('add', '-A');
    await git('commit', '-qm', 'base');

    await git('checkout', '-q', '-b', 'feature');
    await fs.writeFile(path.join(dir, 'feature.js'), 'export const feature = 1;\n');
    await git('add', '-A');
    await git('commit', '-qm', 'feature work');

    // main moves on, independently.
    await git('checkout', '-q', 'main');
    await fs.writeFile(path.join(dir, 'on-main.js'), 'export const onMain = 1;\n');
    await git('add', '-A');
    await git('commit', '-qm', 'unrelated work on main');

    return dir;
}

test('a two-dot range is compared against the merge base', () => {
    const { args, mode } = diffRangeArgs('main..feature');
    assert.deepEqual(args, ['diff', '--unified=3', 'main...feature']);
    assert.equal(mode, 'merge-base');
});

test('an explicit three-dot range is left alone', () => {
    const { args, mode } = diffRangeArgs('main...feature');
    assert.deepEqual(args, ['diff', '--unified=3', 'main...feature']);
    assert.equal(mode, 'merge-base');
});

test('a single revision still means "against the working tree"', () => {
    const { args, mode } = diffRangeArgs('HEAD');
    assert.deepEqual(args, ['diff', '--unified=3', 'HEAD']);
    assert.equal(mode, 'worktree');
});

test('does not report the base branch\'s own commits as part of the change', async () => {
    const dir = await divergedRepo();
    try {
        const files = await collectDiffFiles(
            { range: 'main..feature' },
            { config: { repo: dir } },
        );
        const names = files.map((f) => f.filename).sort();

        assert.deepEqual(
            names, ['feature.js'],
            'the diff includes work done on main, inverted — two-dot semantics',
        );
    } finally {
        await fs.rm(dir, { recursive: true, force: true });
    }
});

/**
 * What `similar_code` searches for.
 *
 * It queried `hunks.slice(0, 2000)` — the RENDERED, already-truncated bundle
 * text. On the review that exposed this, those first 2000 characters were
 * `AI-README.md` prose, so the five retrieved chunks scored 0.149–0.165 and
 * none touched a symbol the change deleted. The query has to be built from what
 * changed, not from how it was printed.
 */

test('the retrieval query is built from symbols and paths, not rendered prose', () => {
    const query = retrievalQueryFor(
        [
            { filename: 'AI-README.md', patch: '@@ -1,1 +1,1 @@\n+Auto-generated by AI. Do not edit.' },
            { filename: 'src/vector-store.service.ts', patch: '@@ -1,1 +1,1 @@\n-  findSimilar() {}' },
        ],
        { symbols: [{ name: 'findSimilar' }], removed: [{ name: 'buildContext' }] },
    );

    assert.match(query, /findSimilar/);
    assert.match(query, /buildContext/);
    assert.match(query, /vector-store\.service/);
    assert.doesNotMatch(query, /Auto-generated/);
});

test('a change with no known symbols still queries its paths', () => {
    const query = retrievalQueryFor(
        [{ filename: 'src/brand-new.ts', patch: '@@ -0,0 +1,1 @@\n+export const x = 1;' }],
        { symbols: [], removed: [] },
    );

    assert.match(query, /brand-new/);
});

test('the query is bounded so it cannot itself become the payload', () => {
    const many = Array.from({ length: 500 }, (_unused, i) => ({
        filename: `src/file-${i}.ts`,
        patch: '',
    }));

    const query = retrievalQueryFor(many, { symbols: [], removed: [] });

    assert.ok(query.length <= 2000, `query is ${query.length} characters`);
});

/**
 * A pull request's head sha.
 *
 * `collectDiffFiles` threw the PR object away and kept only `files`, so the
 * revision the change actually lives at was unavailable — and every `pr_url`
 * review fell back to reading the patch's added lines even when the head was
 * fetched and sitting in the local repository.
 */

test('a local range reports no pull request head', async () => {
    const dir = await divergedRepo();
    try {
        const { files, headSha } = await collectDiffWithMeta(
            { range: 'main..feature' },
            { config: { repo: dir } },
        );
        assert.equal(headSha, null);
        assert.deepEqual(files.map((f) => f.filename), ['feature.js']);
    } finally {
        await fs.rm(dir, { recursive: true, force: true });
    }
});

test('a pasted diff reports no pull request head', async () => {
    const { files, headSha } = await collectDiffWithMeta(
        { diff: 'diff --git a/x.js b/x.js\n--- a/x.js\n+++ b/x.js\n@@ -1,1 +1,1 @@\n-a\n+b\n' },
        { config: { repo: process.cwd() } },
    );
    assert.equal(headSha, null);
    assert.equal(files.length, 1);
});
